In [4]:
import pandas as pd

# Carregando a nossa base de dados
df = pd.read_csv("../DB/safra.csv")

In [2]:
# Repare nos parênteses blindando cada condição!
condicao_and = (df['Safra_KG'] > 2000) & (df['Faturamento_RS'] > 25000)

super_safra = df[condicao_and]
super_safra.head()

  Meses  Safra_KG  Faturamento_RS
3   Abr      3100           31000

In [3]:
# Lembre-se: No Python, usamos dois iguais (==) para comparar se um texto é idêntico ao outro.
condicao_or = (df['Meses'] == 'Jan') | (df['Meses'] == 'Mar')

meses_especificos = df[condicao_or]
meses_especificos.head()

  Meses  Safra_KG  Faturamento_RS
0   Jan      1500           15000
2   Mar      1800           18000